// <auto-generated />
using System;
using Dialysis.Server.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dialysis.Server.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230719083910_IndicatorMigration")]
    partial class IndicatorMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.Shared.Models.ActivePrice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivePrice");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Analysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AnalysisExt")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("GlobalStatusId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("NextDays")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Note2")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Analysise");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.AnalysisResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnalysisDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("AnalysisId")
                        .HasColumnType("bigint");

                    b.Property<string>("AnalysisName")
                        .HasColumnType("text");

                    b.Property<long?>("AnalysisResultGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnalysisResult");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.AnalysisResultGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnalysisDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile1")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile10")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile2")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile3")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile4")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile5")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile6")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile7")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile8")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile9")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnalysisResultGroup");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("District");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Epicrisis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Achtv")
                        .HasColumnType("text");

                    b.Property<string>("ActFile")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("Alt")
                        .HasColumnType("text");

                    b.Property<string>("Ast")
                        .HasColumnType("text");

                    b.Property<string>("AzotAfter")
                        .HasColumnType("text");

                    b.Property<string>("AzotDo")
                        .HasColumnType("text");

                    b.Property<string>("Bilirubin")
                        .HasColumnType("text");

                    b.Property<string>("CaAfter")
                        .HasColumnType("text");

                    b.Property<string>("CaDo")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateVgs")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateVgv")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Days")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<string>("E")
                        .HasColumnType("text");

                    b.Property<string>("Eritropoetin")
                        .HasColumnType("text");

                    b.Property<string>("Erty")
                        .HasColumnType("text");

                    b.Property<string>("Fe")
                        .HasColumnType("text");

                    b.Property<string>("Fosfor")
                        .HasColumnType("text");

                    b.Property<string>("Gemotransfuzii")
                        .HasColumnType("text");

                    b.Property<string>("Gipertenzia")
                        .HasColumnType("text");

                    b.Property<string>("Gipotenzia")
                        .HasColumnType("text");

                    b.Property<long?>("GlobalStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("GolovnoiBol")
                        .HasColumnType("text");

                    b.Property<string>("GruppaKrovi")
                        .HasColumnType("text");

                    b.Property<string>("Ht")
                        .HasColumnType("text");

                    b.Property<string>("Imt")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KAfter")
                        .HasColumnType("text");

                    b.Property<string>("KDo")
                        .HasColumnType("text");

                    b.Property<string>("KreatininAfter")
                        .HasColumnType("text");

                    b.Property<string>("KreatininDo")
                        .HasColumnType("text");

                    b.Property<string>("L")
                        .HasColumnType("text");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Leykty")
                        .HasColumnType("text");

                    b.Property<string>("Lihorodka")
                        .HasColumnType("text");

                    b.Property<string>("M")
                        .HasColumnType("text");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("MedHelpType")
                        .HasColumnType("text");

                    b.Property<string>("MochevinaAfter")
                        .HasColumnType("text");

                    b.Property<string>("MochevinaDo")
                        .HasColumnType("text");

                    b.Property<string>("NaAfter")
                        .HasColumnType("text");

                    b.Property<string>("NaDo")
                        .HasColumnType("text");

                    b.Property<string>("Ng")
                        .HasColumnType("text");

                    b.Property<string>("ObshiyBelok")
                        .HasColumnType("text");

                    b.Property<string>("ObshiyXC")
                        .HasColumnType("text");

                    b.Property<string>("Osl")
                        .HasColumnType("text");

                    b.Property<string>("Osn")
                        .HasColumnType("text");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreparatFe")
                        .HasColumnType("text");

                    b.Property<string>("Preparatov")
                        .HasColumnType("text");

                    b.Property<string>("Pti")
                        .HasColumnType("text");

                    b.Property<string>("Pya")
                        .HasColumnType("text");

                    b.Property<string>("RazmerFiltra")
                        .HasColumnType("text");

                    b.Property<string>("Rw")
                        .HasColumnType("text");

                    b.Property<string>("SaharKrovi")
                        .HasColumnType("text");

                    b.Property<string>("Shok")
                        .HasColumnType("text");

                    b.Property<string>("Soe")
                        .HasColumnType("text");

                    b.Property<string>("Sop")
                        .HasColumnType("text");

                    b.Property<string>("StartHeight")
                        .HasColumnType("text");

                    b.Property<string>("StartWeight")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Sudorogi")
                        .HasColumnType("text");

                    b.Property<string>("Sya")
                        .HasColumnType("text");

                    b.Property<string>("Toshnota")
                        .HasColumnType("text");

                    b.Property<string>("TotalHD")
                        .HasColumnType("text");

                    b.Property<string>("TotalHDF")
                        .HasColumnType("text");

                    b.Property<string>("Tromb")
                        .HasColumnType("text");

                    b.Property<string>("TrombABfist")
                        .HasColumnType("text");

                    b.Property<string>("URR")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Epicrisis");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Consulting")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Eho")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EhoDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ekg")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EkgDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ogk")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OgkDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile1")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile2")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile3")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile4")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile5")
                        .HasColumnType("text");

                    b.Property<string>("UploadFile6")
                        .HasColumnType("text");

                    b.Property<string>("Uzi")
                        .HasColumnType("text");

                    b.Property<string>("Uzi2")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UziDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UziDate2")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("FirstAnalysis");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstAnalysisResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnalysisDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("AnalysisId")
                        .HasColumnType("bigint");

                    b.Property<string>("AnalysisName")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("FirstAnalysisId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Result")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstAnalysisResult");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstCardiovascular", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("AdChastota")
                        .HasColumnType("text");

                    b.Property<string>("AdDefisit")
                        .HasColumnType("text");

                    b.Property<string>("AdProchee")
                        .HasColumnType("text");

                    b.Property<string>("AdRitm")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Drojanie")
                        .HasColumnType("text");

                    b.Property<string>("Epigastralnaia")
                        .HasColumnType("text");

                    b.Property<string>("Granitsa")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Perekardilnaia")
                        .HasColumnType("text");

                    b.Property<string>("Prochee")
                        .HasColumnType("text");

                    b.Property<string>("Prochee2")
                        .HasColumnType("text");

                    b.Property<string>("Prochee3")
                        .HasColumnType("text");

                    b.Property<string>("Prochee4")
                        .HasColumnType("text");

                    b.Property<string>("Shum")
                        .HasColumnType("text");

                    b.Property<string>("Sosudistiy")
                        .HasColumnType("text");

                    b.Property<string>("Ton")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.Property<string>("Verhushechnaia")
                        .HasColumnType("text");

                    b.Property<string>("Vidimye")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstCardiovascular");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstConfectionery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Granitsa")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Jelchniy")
                        .HasColumnType("text");

                    b.Property<string>("Jivot")
                        .HasColumnType("text");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Osmotr")
                        .HasColumnType("text");

                    b.Property<string>("Palypatsia")
                        .HasColumnType("text");

                    b.Property<string>("Perkussia")
                        .HasColumnType("text");

                    b.Property<string>("PodJelchniy")
                        .HasColumnType("text");

                    b.Property<string>("Polost")
                        .HasColumnType("text");

                    b.Property<string>("Prochee")
                        .HasColumnType("text");

                    b.Property<string>("Selezenka")
                        .HasColumnType("text");

                    b.Property<string>("Slizistaia")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.Property<string>("Yazyk")
                        .HasColumnType("text");

                    b.Property<string>("Zev")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstConfectionery");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstEndocrine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Glaznaia")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Potootdelenie")
                        .HasColumnType("text");

                    b.Property<string>("Prochee")
                        .HasColumnType("text");

                    b.Property<string>("Shitovidnaia")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstEndocrine");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstInspection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Anamnez")
                        .HasColumnType("text");

                    b.Property<string>("AnamnezLive")
                        .HasColumnType("text");

                    b.Property<string>("Boli")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Deformatsia")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Grudnoi")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Jivot")
                        .HasColumnType("text");

                    b.Property<string>("Kozhnye")
                        .HasColumnType("text");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Limfaticheskiy")
                        .HasColumnType("text");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Muskulatura")
                        .HasColumnType("text");

                    b.Property<string>("Oteki")
                        .HasColumnType("text");

                    b.Property<string>("Pripuhanie")
                        .HasColumnType("text");

                    b.Property<double?>("Rost")
                        .HasColumnType("double precision");

                    b.Property<string>("Suhost")
                        .HasColumnType("text");

                    b.Property<string>("Svet")
                        .HasColumnType("text");

                    b.Property<string>("Syp")
                        .HasColumnType("text");

                    b.Property<string>("Tela")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.Property<string>("Uprugost")
                        .HasColumnType("text");

                    b.Property<double?>("Ves")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("FirstInspection");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstNeuro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Date1")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Date2")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dvijenie")
                        .HasColumnType("text");

                    b.Property<string>("Glaznye")
                        .HasColumnType("text");

                    b.Property<string>("Glotochnyi")
                        .HasColumnType("text");

                    b.Property<string>("Golovokrujenie")
                        .HasColumnType("text");

                    b.Property<string>("Intellect")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Kerniga")
                        .HasColumnType("text");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Litso")
                        .HasColumnType("text");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Meningealnye")
                        .HasColumnType("text");

                    b.Property<string>("Mnitelnost")
                        .HasColumnType("text");

                    b.Property<string>("Pamiat")
                        .HasColumnType("text");

                    b.Property<string>("Pohodka")
                        .HasColumnType("text");

                    b.Property<string>("Potologicheskie")
                        .HasColumnType("text");

                    b.Property<string>("Poverhnostnye")
                        .HasColumnType("text");

                    b.Property<string>("Rech")
                        .HasColumnType("text");

                    b.Property<string>("Romberga")
                        .HasColumnType("text");

                    b.Property<string>("Sindrom")
                        .HasColumnType("text");

                    b.Property<string>("Soznanye")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.Property<string>("Vnushaemost")
                        .HasColumnType("text");

                    b.Property<string>("Yazyk")
                        .HasColumnType("text");

                    b.Property<string>("Zrachki")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstNeuro");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstRespiratory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Chastota")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dyhatelnye")
                        .HasColumnType("text");

                    b.Property<string>("Glubina")
                        .HasColumnType("text");

                    b.Property<string>("Golosovoe")
                        .HasColumnType("text");

                    b.Property<string>("Grudnaia")
                        .HasColumnType("text");

                    b.Property<string>("Grudnoi")
                        .HasColumnType("text");

                    b.Property<string>("Hrip")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nosovoe")
                        .HasColumnType("text");

                    b.Property<string>("Prochee")
                        .HasColumnType("text");

                    b.Property<string>("Sravnitelnaia")
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .HasColumnType("text");

                    b.Property<string>("Topograficheskaia")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstRespiratory");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.FirstUrogenital", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Chastota")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<string>("MochevoiPalpatsia")
                        .HasColumnType("text");

                    b.Property<string>("MochevoiPerkissia")
                        .HasColumnType("text");

                    b.Property<string>("MochevoiProchee")
                        .HasColumnType("text");

                    b.Property<string>("Nederjanie")
                        .HasColumnType("text");

                    b.Property<string>("PochkiPalpatsia")
                        .HasColumnType("text");

                    b.Property<string>("PochkiProchee")
                        .HasColumnType("text");

                    b.Property<string>("PochkiSimptom")
                        .HasColumnType("text");

                    b.Property<string>("Prochee")
                        .HasColumnType("text");

                    b.Property<string>("Rezi")
                        .HasColumnType("text");

                    b.Property<string>("Sutochnoe")
                        .HasColumnType("text");

                    b.Property<string>("SvetMochi")
                        .HasColumnType("text");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FirstUrogenital");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.GlobalStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GlobalStatus");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.GroupLPU", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupLPU");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.GroupPersonTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupPersonTitle");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.GroupReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupReason");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.HDSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Access")
                        .HasColumnType("text");

                    b.Property<decimal?>("ActivePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Anticoagulation")
                        .HasColumnType("text");

                    b.Property<string>("Complaints")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<string>("Correction")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dia")
                        .HasColumnType("text");

                    b.Property<string>("Dialyzer")
                        .HasColumnType("text");

                    b.Property<string>("Durators")
                        .HasColumnType("text");

                    b.Property<string>("EndDia")
                        .HasColumnType("text");

                    b.Property<string>("EndRitm")
                        .HasColumnType("text");

                    b.Property<string>("EndSys")
                        .HasColumnType("text");

                    b.Property<string>("EndTemp")
                        .HasColumnType("text");

                    b.Property<double?>("EndWeight")
                        .HasColumnType("double precision");

                    b.Property<long?>("FinishedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("IdentifyBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IdentifyOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageEnd")
                        .HasColumnType("text");

                    b.Property<string>("ImageStart")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("MachineId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MedCardId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Note2")
                        .HasColumnType("text");

                    b.Property<string>("Note3")
                        .HasColumnType("text");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Program")
                        .HasColumnType("text");

                    b.Property<string>("Reinfusion")
                        .HasColumnType("text");

                    b.Property<string>("Ritm")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SessionEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SessionStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("SetPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Speed")
                        .HasColumnType("text");

                    b.Property<double?>("StartWeight")
                        .HasColumnType("double precision");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sys")
                        .HasColumnType("text");

                    b.Property<string>("Temp")
                        .HasColumnType("text");

                    b.Property<double?>("TotalHours")
                        .HasColumnType("double precision");

                    b.Property<double?>("TotalMinutes")
                        .HasColumnType("double precision");

                    b.Property<string>("TypeDialyzer")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HDSession");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.HDSessionHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Dia")
                        .HasColumnType("text");

                    b.Property<long>("HDSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Hour")
                        .HasColumnType("text");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Ritm")
                        .HasColumnType("text");

                    b.Property<string>("Sys")
                        .HasColumnType("text");

                    b.Property<string>("Temp")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HDSessionHour");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.HDSessionPause", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("HDSessionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PauseEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PauseStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("TotalMinutes")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("HDSessionPause");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Indicator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Indicator");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.IndicatorReference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IndicatorReference");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.IndicatorRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Change1")
                        .HasColumnType("double precision");

                    b.Property<double?>("Change2")
                        .HasColumnType("double precision");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Fact1")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fact2")
                        .HasColumnType("double precision");

                    b.Property<long>("IndicatorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("Plan1")
                        .HasColumnType("double precision");

                    b.Property<double?>("Plan2")
                        .HasColumnType("double precision");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Threshold")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("IndicatorRow");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.MedCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActFile")
                        .HasColumnType("text");

                    b.Property<string>("Alchohol")
                        .HasColumnType("text");

                    b.Property<string>("AllergoAnamez")
                        .HasColumnType("text");

                    b.Property<string>("Blood")
                        .HasColumnType("text");

                    b.Property<string>("Chesotka")
                        .HasColumnType("text");

                    b.Property<string>("Complication1")
                        .HasColumnType("text");

                    b.Property<string>("Complication2")
                        .HasColumnType("text");

                    b.Property<string>("Complication3")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Diagnosis1")
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis2")
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis3")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DirectionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("DirectorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Fluorografia")
                        .HasColumnType("text");

                    b.Property<long?>("GlobalStatusId")
                        .HasColumnType("bigint");

                    b.Property<string>("IndividualPlan")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("M3")
                        .HasColumnType("text");

                    b.Property<string>("MainDiagnosis")
                        .HasColumnType("text");

                    b.Property<string>("MedCardNumber")
                        .HasColumnType("text");

                    b.Property<long>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Obosnovanie")
                        .HasColumnType("text");

                    b.Property<string>("OtherAB")
                        .HasColumnType("text");

                    b.Property<string>("OutcomeTreatment")
                        .HasColumnType("text");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Pedikulez")
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Recommendation")
                        .HasColumnType("text");

                    b.Property<string>("Resus")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("TotalHDSession")
                        .HasColumnType("integer");

                    b.Property<string>("UniqId")
                        .HasColumnType("text");

                    b.Property<string>("Vassermana")
                        .HasColumnType("text");

                    b.Property<string>("Vgs")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VgsDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Vgv")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VgvDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Vich")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VichDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("MedCard");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.MedCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedCenter");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.MedCenterFiles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("IsDownload")
                        .HasColumnType("text");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedCenterFiles");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.MedCenterMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CertificateCountry")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CertificateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CertificateHolder")
                        .HasColumnType("text");

                    b.Property<string>("CertificateHolderCountry")
                        .HasColumnType("text");

                    b.Property<string>("CertificateMedCenterId")
                        .HasColumnType("text");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("text");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LicenseCountry")
                        .HasColumnType("text");

                    b.Property<string>("ManCountry")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<long>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PermitDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PermitName")
                        .HasColumnType("text");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("text");

                    b.Property<string>("PermitSeria")
                        .HasColumnType("text");

                    b.Property<long?>("TotalSessions")
                        .HasColumnType("bigint");

                    b.Property<string>("UpFile1")
                        .HasColumnType("text");

                    b.Property<string>("UpFile2")
                        .HasColumnType("text");

                    b.Property<string>("UpFile3")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedCenterMachine");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.MedCenterUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MedCenterUser");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<long?>("GroupActId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupText")
                        .HasColumnType("text");

                    b.Property<string>("Image1")
                        .HasColumnType("text");

                    b.Property<string>("Image2")
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<long?>("MedCenterId")
                        .HasColumnType("bigint");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Phone2")
                        .HasColumnType("text");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StatusId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.PatientGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientGroup");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.PatientGroupPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("GroupTitleId")
                        .HasColumnType("bigint");

                    b.Property<string>("PersonFio")
                        .HasColumnType("text");

                    b.Property<long>("PersonTitleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PatientGroupAct");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.PatientGroupTitle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SignFile")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientGroupTitle");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.PatientHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("GroupFromId")
                        .HasColumnType("bigint");

                    b.Property<long>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GroupLPUId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GroupReasonId")
                        .HasColumnType("bigint");

                    b.Property<string>("GroupText")
                        .HasColumnType("text");

                    b.Property<long>("GroupTitleId")
                        .HasColumnType("bigint");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientHistory");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.PatientStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PatientStatus");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.Status", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastIp")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MIddleName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.UserProfileRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserProfileRole");
                });

            modelBuilder.Entity("Dialysis.Shared.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
